# Generated by Django 3.1.1 on 2023-12-17 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(default=1, verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_date', models.DateField(default=datetime.date(2023, 12, 17), verbose_name='Дата утверждения')),
                ('discipline', models.ManyToManyField(to='main.Discipline')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.syllabus'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ManyToManyField(to='main.Teacher'),
        ),
        migrations.CreateModel(
            name='CompletedDisciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=100, verbose_name='Количество часов')),
                ('mark', models.CharField(default='Зачет', max_length=10, verbose_name='Оценка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discipline')),
            ],
            options={
                'verbose_name': 'Завершенная дисциплина',
                'verbose_name_plural': 'Завершенные дисциплины',
            },
        ),
        migrations.CreateModel(
            name='RecordBook',
            fields=[
                ('number', models.PositiveBigIntegerField(verbose_name='Номер зачетной книжки')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.student')),
                ('completed_disciplines', models.ManyToManyField(to='main.CompletedDisciplines')),
            ],
            options={
                'verbose_name': 'Зачетная книжка',
                'verbose_name_plural': 'Зачетные книжки',
            },
        ),
    ]
