# Generated by Django 3.1.1 on 2023-12-21 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_syllabus_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='type_of_assesment',
            field=models.CharField(default='Зачет', max_length=50, verbose_name='Вид оценивания'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='set_date',
            field=models.DateField(default=datetime.date(2023, 12, 21), verbose_name='Дата утверждения'),
        ),
    ]
