# Generated by Django 5.0 on 2023-12-24 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_user_alter_syllabus_set_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='set_date',
            field=models.DateField(default=datetime.date(2023, 12, 25), verbose_name='Дата утверждения'),
        ),
    ]
