# Generated by Django 5.0 on 2023-12-28 19:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_student_user_alter_syllabus_set_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='set_date',
            field=models.DateField(default=datetime.date(2023, 12, 28), verbose_name='Дата утверждения'),
        ),
    ]
